# Numpy

1. Fundamentos de NumPy
    - Arrays NumPy
    - Tipos de datos en NumPy
    - Creación de arrays
    - Acceso a elementos y slicing
    - Atributos de los arrays (forma, tamaño, tipo de dato)
    - Manipulación de dimensiones
2. Operaciones básicas con NumPy
    - Operaciones aritméticas
    - Operaciones lógicas
    - Funciones universales (ufuncs)
    - Broadcasting
3. Indexado y slicing avanzado
    - Indexado con arrays booleanos
    - Indexado con arrays enteros
    - Indexado con condiciones lógicas
4. Manipulación de arrays
    - Concatenación de arrays
    - División de arrays
    - Transposición de arrays
    - Cambio de forma (reshaping)
    - Aplanamiento de arrays (ravel, flatten)
5. Funciones matemáticas y estadísticas
    - Funciones matemáticas básicas
    - Funciones estadísticas básicas
    - Álgebra lineal con NumPy (álgebra de matrices, cálculo de determinantes, resolución de sistemas de ecuaciones)
6. Generación de números aleatorios
    - Generación de números aleatorios simples
    - Distribuciones de probabilidad
7. Guardado y carga de datos
    - Guardado de arrays en archivos
    - Carga de arrays desde archivos
8. NumPy y la visualización de datos
    - Integración con Matplotlib
    - Representación de arrays NumPy
9. Optimización de código con NumPy
    - Vectorización de operaciones
    - Comparación de rendimiento con listas estándar de Python
10. Casos de uso y ejemplos prácticos
    - Procesamiento de imágenes
    - Cálculos científicos y de ingeniería
    - Análisis de datos

In [1]:
import numpy as np

## Fundamentos de Numpy

### Arrays Numpy

In [2]:
# Crear un array unidimensional
arr1d = np.array([1, 2, 3, 4, 5])

type(arr1d) # numpy.ndarray
print("Array NumPy:", arr1d)

Array NumPy: [1 2 3 4 5]


### Tipos de datos en NumPy

In [3]:
# Tipos de datos enteros
np.int8    # Entero de 8 bits con signo
np.int16   # Entero de 16 bits con signo
np.int32   # Entero de 32 bits con signo
np.int64   # Entero de 64 bits con signo

# Tipos de datos enteros sin signo
np.uint8   # Entero de 8 bits sin signo
np.uint16  # Entero de 16 bits sin signo
np.uint32  # Entero de 32 bits sin signo
np.uint64  # Entero de 64 bits sin signo

# Tipos de datos de punto flotante
np.float16  # Flotante de 16 bits
np.float32  # Flotante de 32 bits
np.float64  # Flotante de 64 bits (doble precisión)
np.float128 # Flotante de 128 bits (precisión extendida)

# Otros tipos de datos
np.bool    # Tipo booleano (True o False)
np.complex64  # Número complejo de 64 bits (parte real e imaginaria de 32 bits)
np.complex128 # Número complejo de 128 bits (parte real e imaginaria de 64 bits)
np.complex256 # Número complejo de 256 bits (parte real e imaginaria de 128 bits)

# Tipo de dato para texto (cadena de caracteres)
np.str_    # Tipo de cadena de longitud fija

# Tipo de dato para objetos de Python
np.object  # Tipo de objeto de Python

# Tipo de dato para valores de bytes
np.bytes_  # Tipo de cadena de bytes de longitud fija

# Tipo de dato para fechas y horas
np.datetime64 # Tipo de fecha y hora
np.timedelta64 # Tipo de diferencia entre fechas y horas

AttributeError: module 'numpy' has no attribute 'float128'

### Creación de arrays

In [4]:
# Crear una array a partir de una lista
array_lista = np.array([1, 2, 3, 4, 5])

# Crear una array de ceros
array_ceros = np.zeros((2, 3))  # Una matriz de 2x3 con todos los elementos cero

# Crear una array de unos
array_unos = np.ones((3, 2))     # Una matriz de 3x2 con todos los elementos uno

# Crear una array con valores constantes
valor_constante = 5
array_constante = np.full((2, 2), valor_constante)  # Una matriz de 2x2 con todos los elementos iguales a 5

# Crear una array con una secuencia de números
array_secuencia = np.arange(0, 10, 2)  # Una secuencia del 0 al 9 (exclusivo) con paso de 2

# Crear una array de números espaciados de manera uniforme
array_espaciada = np.linspace(0, 1, 5)  # Una secuencia de 5 números uniformemente espaciados entre 0 y 1

# Crear una array con números aleatorios
array_aleatorio = np.random.rand(2, 3)  # Una matriz de 2x3 con valores aleatorios entre 0 y 1

# np.where: Retorna elementos de x o y según la condición.
array_condicion = np.array([True, False, True, False])
array_x = np.array([1, 2, 3, 4])
array_y = np.array([5, 6, 7, 8])

resultado_where = np.where(array_condicion, array_x, array_y) # [1 6 3 8]

# np.diag: Extrae la diagonal o construye una matriz diagonal.
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

diagonal_principal = np.diag(matriz) # [1 5 9]

### Indexación y slicing

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Indexación básica
array_ejemplo[0]        # La primera fila del array
array_ejemplo[0][1]     # El segundo elemento de la primera fila
array_ejemplo[2, 1]     # Otra forma de acceder al segundo elemento de la tercera fila

# Slicing básico
array_ejemplo[0:2]      # Las dos primeras filas del array
array_ejemplo[:, 1]     # La segunda columna del array
array_ejemplo[1:, :2]   # Desde la segunda fila hasta el final y las dos primeras columnas

# Indexación con arrays booleanos (masking)
mask = array_ejemplo > 5 # Crear una máscara booleana basada en la condición
array_ejemplo[mask]      # Los elementos del array que cumplen la condición

# Indexación con arrays de índices
indices = np.array([0, 2]) # Un array de índices
array_ejemplo[indices]     # Los elementos del array en los índices dados

# Indexación con paso
array_ejemplo[::2]      # Cada segundo elemento a lo largo del eje 0 (filas)
array_ejemplo[:, ::-1]  # Invertir el orden de las columnas

# Indexación con números negativos
array_ejemplo[-1]       # La última fila del array
array_ejemplo[:-1]      # Todas las filas excepto la última

# Indexación y slicing en arrays de más de una dimensión
array_3d = np.arange(27).reshape((3, 3, 3))  # Un array 3D de ejemplo
array_3d[0, :, 1]                            # La segunda columna de la primera matriz

### Atributos de los arrays

In [ ]:
array = np.array([[1,2,3],[4,5,6]])

# Acceder a los atributos de las arrays
array.shape # Forma de la array
array.ndim # Número de dimensiones
array.size # Número total de elementos
array.dtype # Tipo de datos de la array
array.itemsize # Tamaño en bytes de cada elemento
array.nbytes # Tamaño total de la array en bytes

### Manipulación de dimensiones

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Transposición de un array
array_transpuesto = np.transpose(array_ejemplo)  # Transponer el array
array_ejemplo.T  # Otra forma de transponer el array

# Cambiar la forma (reshape) de un array
array_reshape = np.reshape(array_ejemplo, (1, 9))  # Cambiar a una fila de 9 elementos
array_reshape2 = array_ejemplo.reshape(1, -1)       # Otra forma de cambiar a una fila

# Agregar una nueva dimensión a un array existente
array_nueva_dim = np.expand_dims(array_ejemplo, axis=2)  # Agregar una nueva dimensión al final
array_nueva_dim2 = np.expand_dims(array_ejemplo, axis=0)  # Agregar una nueva dimensión al principio

# Eliminar dimensiones de tamaño 1
array_sin_una_dim = np.squeeze(array_nueva_dim)  # Eliminar la dimensión agregada anteriormente

# Concatenar arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
array_concatenado = np.concatenate((array1, array2), axis=0)  # Concatenar a lo largo del eje 0 (filas)

## Operaciones básicas con NumPy

### Operaciones aritméticas

In [ ]:

# Crear dos arrays de ejemplo
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Suma de arrays
suma_arrays = array1 + array2  # Suma elemento por elemento
suma_arrays2 = np.add(array1, array2)  # Otra forma de sumar

# Resta de arrays
resta_arrays = array1 - array2  # Resta elemento por elemento
resta_arrays2 = np.subtract(array1, array2)  # Otra forma de restar

# Multiplicación de arrays
multiplicacion_arrays = array1 * array2  # Multiplicación elemento por elemento
multiplicacion_arrays2 = np.multiply(array1, array2)  # Otra forma de multiplicar

# División de arrays
division_arrays = array1 / array2  # División elemento por elemento
division_arrays2 = np.divide(array1, array2)  # Otra forma de dividir

# Operaciones aritméticas con escalares
escalar = 2
multiplicacion_escalar = escalar * array1  # Multiplicar todos los elementos por el escalar
suma_escalar = escalar + array1  # Sumar el escalar a todos los elementos

# Operaciones matriciales
producto_punto = np.dot(array1, array2)  # Producto punto entre arrays
producto_matricial = np.matmul(array1, array2)  # Producto matricial

# Otras operaciones aritméticas
suma_total = np.sum(array1)  # Suma de todos los elementos del array
promedio = np.mean(array1)   # Promedio de todos los elementos del array

### Operaciones lógicas

In [ ]:
# Crear dos arrays de ejemplo
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Operaciones lógicas elemento por elemento
resultado_and = np.logical_and(array1 > 2, array2 < 7)  # Operación AND
resultado_or = np.logical_or(array1 > 2, array2 < 7)    # Operación OR
resultado_not = np.logical_not(array1 > 2)              # Operación NOT

# Comprobar si todos o alguno de los elementos son verdaderos
todos_verdaderos = np.all(array1 > 0)     # ¿Todos los elementos son mayores que 0?
alguno_verdadero = np.any(array1 == 2)    # ¿Alguno de los elementos es igual a 2?

# Comparaciones
comparacion_mayor = array1 > array2   # Comparación de elementos mayor que
comparacion_igual = array1 == array2  # Comparación de elementos iguales

### Funciones universales

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([1, 2, 3, 4, 5])

# Funciones matemáticas
cuadrado = np.square(array_ejemplo)   # Elevar al cuadrado cada elemento
raiz_cuadrada = np.sqrt(array_ejemplo) # Raíz cuadrada de cada elemento
exponencial = np.exp(array_ejemplo)    # Exponencial de cada elemento
logaritmo = np.log(array_ejemplo)      # Logaritmo natural de cada elemento

# Funciones trigonométricas
seno = np.sin(array_ejemplo)   # Seno de cada elemento (en radianes)
coseno = np.cos(array_ejemplo) # Coseno de cada elemento (en radianes)
tangente = np.tan(array_ejemplo) # Tangente de cada elemento (en radianes)

# Funciones de comparación
mayor_que_cinco = np.greater(array_ejemplo, 5)  # Comparar si cada elemento es mayor que 5
igual_a_tres = np.equal(array_ejemplo, 3)       # Comparar si cada elemento es igual a 3

# Funciones de redondeo
redondeo = np.round([0.5, 1.5, 2.5, 3.5, 4.5])  # Redondear cada número al entero más cercano
techo = np.ceil([0.1, 1.9, 2.5, 3.6, 4.2])       # Redondear hacia arriba
piso = np.floor([0.1, 1.9, 2.5, 3.6, 4.2])       # Redondear hacia abajo

### Broadcasting

In [ ]:
# Crear un array de ejemplo
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Sumar un escalar a cada elemento del array
resultado = array1 + 1
# El escalar 1 se expande automáticamente para que tenga la misma forma que array1

# Multiplicar un vector fila por cada fila del array
vector_fila = np.array([10, 20, 30])
resultado = array1 + vector_fila
# El vector_fila se expande automáticamente para que tenga la misma forma que array1

# Sumar un vector columna por cada columna del array
vector_columna = np.array([[100], [200]])
resultado = array1 + vector_columna
# El vector_columna se expande automáticamente para que tenga la misma forma que array1

# Broadcasting con arrays de diferentes formas
array2 = np.array([1, 2])
resultado = array1 + array2
# operands could not be broadcast together with shapes (2,3) (2,) 

# Broadcasting con arrays de diferentes formas - Caso no compatible
array3 = np.array([[1], [2], [3]])
# array1 + array3 generará un error ya que las formas no son compatibles

## Indexado y slicing avanzado

### Indexado con arrays booleanos

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Crear una máscara booleana basada en una condición
condicion = array_ejemplo > 5
# La condición devuelve un array booleano con True en las posiciones donde la condición se cumple

# Usar la máscara booleana para seleccionar elementos del array original
elementos_seleccionados = array_ejemplo[condicion]
# Selecciona los elementos de array_ejemplo donde la condición es True

# También puedes realizar la operación en una sola línea
elementos_seleccionados = array_ejemplo[array_ejemplo > 5]

# Modificar los valores seleccionados
array_ejemplo[array_ejemplo > 5] = 0
# Asigna 0 a los elementos de array_ejemplo donde la condición es True

# Otra forma de usar masking con múltiples condiciones
condicion_multiple = (array_ejemplo > 2) & (array_ejemplo < 7)
elementos_seleccionados = array_ejemplo[condicion_multiple]

### Indexado con condiciones lógicas

In [27]:

# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Seleccionar elementos mayores que un valor específico
mayor_que_cinco = array_ejemplo[array_ejemplo > 5]

# Seleccionar elementos que cumplen múltiples condiciones
cumple_condiciones = array_ejemplo[(array_ejemplo > 2) & (array_ejemplo < 7)]

# Seleccionar elementos que cumplen al menos una condición
al_menos_una_condicion = array_ejemplo[(array_ejemplo == 2) | (array_ejemplo == 6)]

# Seleccionar elementos que no cumplen una condición
no_cumple_condicion = array_ejemplo[~(array_ejemplo > 5)]

# También podemos usar funciones NumPy para crear condiciones
condicion_negativa = array_ejemplo[np.logical_not(array_ejemplo > 5)]

# Podemos combinar condiciones lógicas y matemáticas
resultado = array_ejemplo[(array_ejemplo + 2) > 5]

# También podemos usar condiciones lógicas con arrays multidimensionales
array_3d = np.random.randint(0, 10, size=(3, 3, 3))
resultado_3d = array_3d[array_3d[:, :, 0] > 5]

## Manipulación de arrays

### Concatenación de arrays

In [ ]:
# Concatenación de arrays 1D
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenar a lo largo del eje 0 (por defecto para arrays 1D)
concatenacion_1d = np.concatenate((array1, array2))

# Concatenación de arrays 2D
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matriz2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Concatenar a lo largo del eje 0 (filas)
concatenacion_filas = np.concatenate((matriz1, matriz2), axis=0)

# Concatenar a lo largo del eje 1 (columnas)
concatenacion_columnas = np.concatenate((matriz1, matriz2), axis=1)

# También podemos usar vstack y hstack para concatenar específicamente a lo largo de un eje
concatenacion_vertical = np.vstack((matriz1, matriz2))  # Equivalente a axis=0
concatenacion_horizontal = np.hstack((matriz1, matriz2))  # Equivalente a axis=1

# Concatenación de arrays 3D
array3d_1 = np.random.randint(0, 10, size=(2, 2, 2))
array3d_2 = np.random.randint(0, 10, size=(2, 2, 2))

# Concatenar a lo largo del eje 0 (profundidad)
concatenacion_3d = np.concatenate((array3d_1, array3d_2), axis=0)

### División de arrays

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.arange(1, 13).reshape(3, 4)
"""
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
"""

# Dividir el array en partes a lo largo del eje horizontal (eje 1)
partes_horizontal = np.split(array_ejemplo, 2, axis=1)
"""
[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]
"""

# Dividir el array en partes a lo largo del eje vertical (eje 0)
partes_vertical = np.split(array_ejemplo, 3, axis=0)
"""
[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]])]
"""

# Dividir el array en partes desiguales
partes_desiguales = np.array_split(array_ejemplo, [2, 3], axis=1)
"""
[array([[1, 2],
        [5, 6],
        [9, 10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]
"""

# Dividir el array verticalmente en la segunda columna
split_vertical = np.hsplit(array_ejemplo, [2])
"""
[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]
"""

# Dividir el array horizontalmente en la segunda fila
split_horizontal = np.vsplit(array_ejemplo, [1])
"""
[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]
"""

### Transposición de arrays

In [ ]:

# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6]])

# Transposición utilizando np.transpose()
transpuesto_np = np.transpose(array_ejemplo)
# También se puede usar array_ejemplo.T para transponer
transpuesto_attr = array_ejemplo.T

### Cambio de forma

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6]])

# Cambiar la forma del array a un vector fila (1D)
vector_fila = array_ejemplo.reshape(1, -1)
# El argumento -1 le dice a NumPy que determine automáticamente el tamaño de la segunda dimensión

# Cambiar la forma del array a un vector columna (1D)
vector_columna = array_ejemplo.reshape(-1, 1)

# Cambiar la forma del array a una matriz de 1 fila y 6 columnas
matriz_1x6 = np.reshape(array_ejemplo, (1, 6))

# Cambiar la forma del array a una matriz de 3 filas y 2 columnas
matriz_3x2 = np.reshape(array_ejemplo, (3, 2))

### Aplanamiento de arrays

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6]])

# Aplanar el array utilizando el método flatten()
array_aplanado_metodo = array_ejemplo.flatten()

# Aplanar el array utilizando la función np.flatten()
array_aplanado_funcion = np.flatten(array_ejemplo)

## Funciones matemáticas y estadísticas

### Funciones matemáticas básicas

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6]])

# Suma de todos los elementos del array
suma_total = np.sum(array_ejemplo)

# Suma a lo largo de un eje específico (eje 0: columnas, eje 1: filas)
suma_columnas = np.sum(array_ejemplo, axis=0)
suma_filas = np.sum(array_ejemplo, axis=1)

# Producto de todos los elementos del array
producto_total = np.prod(array_ejemplo)

# Producto a lo largo de un eje específico
producto_columnas = np.prod(array_ejemplo, axis=0)
producto_filas = np.prod(array_ejemplo, axis=1)

# Media de todos los elementos del array
media = np.mean(array_ejemplo)

# Mínimo y máximo
minimo = np.min(array_ejemplo)
maximo = np.max(array_ejemplo)

# Raíz cuadrada de cada elemento del array
raiz_cuadrada = np.sqrt(array_ejemplo)

# Exponencial de cada elemento del array
exponencial = np.exp(array_ejemplo)

# Logaritmo natural de cada elemento del array
logaritmo = np.log(array_ejemplo)

# Seno de cada elemento del array (en radianes)
seno = np.sin(array_ejemplo)

# Coseno de cada elemento del array (en radianes)
coseno = np.cos(array_ejemplo)

# Tangente de cada elemento del array (en radianes)
tangente = np.tan(array_ejemplo)

### Funciones estadísticas básicas

In [ ]:
# Crear un array de ejemplo
array_ejemplo = np.array([[1, 2, 3],
                          [4, 5, 6]])

# Suma de todos los elementos del array
suma_total = np.sum(array_ejemplo)

# Media de todos los elementos del array
media = np.mean(array_ejemplo)

# Mediana de todos los elementos del array
mediana = np.median(array_ejemplo)

# Desviación estándar de todos los elementos del array
desviacion_estandar = np.std(array_ejemplo)

# Varianza de todos los elementos del array
varianza = np.var(array_ejemplo)

# Mínimo y máximo
minimo = np.min(array_ejemplo)
maximo = np.max(array_ejemplo)

# Percentiles
percentil_25 = np.percentile(array_ejemplo, 25)
percentil_75 = np.percentile(array_ejemplo, 75)

# Correlación
correlacion = np.corrcoef(array_ejemplo)

# Covarianza
covarianza = np.cov(array_ejemplo)

# Conteo de elementos no cero
elementos_no_cero = np.count_nonzero(array_ejemplo)

# Conteo de elementos únicos y sus ocurrencias
elementos_unicos, ocurrencias = np.unique(array_ejemplo, return_counts=True)

### Álgebra lineal con NumPy

In [ ]:

# Crear matrices de ejemplo
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Multiplicación de matrices
producto_matricial = np.dot(A, B)
# También puedes usar el operador @ para multiplicación de matrices
producto_matricial_alt = A @ B

# Transpuesta de una matriz
transpuesta = np.transpose(A)
# Otra forma de transponer es usar el atributo T
transpuesta_alt = A.T

# Inversa de una matriz
inversa = np.linalg.inv(A)

# Determinante de una matriz
determinante = np.linalg.det(A)

# Valores propios y vectores propios de una matriz
valores_propios, vectores_propios = np.linalg.eig(A)

# Resolver un sistema de ecuaciones lineales Ax = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)

# Descomposición en valores singulares (SVD)
U, S, V = np.linalg.svd(A)

## Generación de números aleatorios

### Generación de números aleatorios simples

In [ ]:

# Generar un número aleatorio entre 0 y 1
numero_aleatorio = np.random.random()

# Generar un array de números aleatorios entre 0 y 1 de una dimensión
array_aleatorio = np.random.rand(5)

# Generar un array de números aleatorios de una dimensión dentro de un rango específico
array_aleatorio_rango = np.random.randint(1, 10, size=5)

# Generar un array de números aleatorios de múltiples dimensiones
array_aleatorio_multi = np.random.randn(2, 3)  # Distribución normal estándar

# Mezclar un array
array_original = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array_original)

# Elegir elementos aleatorios de un array
array_ejemplo = np.array(['a', 'b', 'c', 'd', 'e'])
elementos_elegidos = np.random.choice(array_ejemplo, size=3, replace=False)

### Distribuciones de probabilidad

In [ ]:
# Distribución uniforme
uniforme = np.random.uniform(low=0.0, high=1.0, size=10)

# Distribución normal (Gaussiana)
normal = np.random.normal(loc=0.0, scale=1.0, size=10)

# Distribución binomial
binomial = np.random.binomial(n=10, p=0.5, size=10)

# Distribución de Poisson
poisson = np.random.poisson(lam=3.0, size=10)

## Guardado y carga de datos

### Guardado de arrays en archivos

### Carga de arrays desde archivos

## NumPy y la visualización de datos

### Integración con Matplotlib

### Representación de arrays NumPy

## Optimización de código con NumPy

### Vectorización de operaciones

### Comparación de rendimiento con listas estándar de Python

## Casos de uso y ejemplos prácticos

### Procesamiento de imágenes

### Cálculos científicos y de ingeniería

### Cálculos científicos y de ingeniería